### ISSUE TITLE
Add QoS to cake-wg-pbr

### ISSUE THREAD

**Issue by Rexadev** [lynxthecat/cake-wg-pbr#2]

**Comment by lynxthecat** [comment]
@Rexadev I looked into this and it is not practical in cake-wg-pbr because WireGuard strips out DSCPs during encapsulation and so we would need to either: restore them using [this script](https://github.com/xdp-project/bpf-examples/tree/master/preserve-dscp) - see [here](https://forum.openwrt.org/t/qosify-new-package-for-dscp-marking-cake/111789/1041?u=lynx) for background information; or use a different approach like [cake-dual-ifb](https://github.com/lynxthecat/cake-dual-ifb).

Therefore if you want to use QoS in the context of VPN with PBR I would suggest you use cake-dual-ifb instead. But you should probably consider whether the extra complexity is warranted. The cake algorithm does an excellent job by default without all the hassle associated with tinkering with DSCPs - see [here](https://forum.openwrt.org/t/nftables-and-qos-in-2021/112013/517?u=lynx).
